### ISSUE TITLE
transport rpc request directly to endpoint if this method is not in registered list

### ISSUE THREAD

**Issue by atenjin** [alt-research/subway#24]
for the limit of the jsonrpc lib, the proxied rpc must know the method name first, then register into jsonrpc.

but in fact in production env, we may do not know the method name first.

for most of time, we may can add those method when we see the error msg? or some thing to tell us this method is not supported yet.

so we may consider to add this feature to allow the unregistered method can transport direclty to the endpoint rather then return some error? 

I think at least need the following feature:

- [ ] 1. then proxy receive a method which is not in the registed method list, we need at least print a error log, and log in metrics.
- [ ] 2. transport those requests to endpoint

**Comment by koushiro** [comment]
If some rpc methods are not supported by the jsonrpc server, the server will return a `method not found` error response.
So I think these demands are unreasonable and we need to close this issue.

PS: there is another RPC method called `rpc_methods` that returns all the RPC methods supported by the server.

**Comment by koushiro** [comment]
Closed, can be reopened if needed
